### ISSUE TITLE
Plugin crash (terminate called after throwing an instance of std::invalid_argument)

### ISSUE THREAD

**Issue by lukaszolek** [da-anda/hass-io-addons#12]
I upgraded HA, Supervisor and KNXD to the newest versions and I get following error.

KNXD config:
- interface: usb
- address: 0.0.1
- client_address: 0.0.2:8
- device: /dev/ttyAMA0
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: KNXD daemon
 KNXD daemon you can use to create a KNX/IP gateway via TPUART or USB bus adapters
-----------------------------------------------------------
 Add-on version: 0.3.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.11  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.2.1
 Home Assistant Supervisor: 2021.02.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 2-init-config: executing... 
[cont-init.d] 2-init-config: exited 0.
[cont-init.d] done.
[services.d] starting services
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
[services.d] done.
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
```

**Comment by da-anda** [comment]
well, the knxd version itself did not change between 0.3.6 and 0.3.7, so it can't really be knxd related. I only switched the base image to the new Github container repository hosted ones and fixed a runtime issue because those new base images missed two libs that knxd required.
Still on OS 5.10 myself though, will update to 5.11 later today and see if the issue is showing up on my end as well. Can't reproduce so far though, but I also don't use the USB interface but `TPUART`.

**Comment by da-anda** [comment]
hmm, no issues on my end on 5.11. Are you sure your device `ttyAMA0` is needing the `USB` interface? For me this device is `TPUART`

**Comment by lukaszolek** [comment]
You're right, after update I lost my original configuration and needed to recreate it. I had problems with "device" parameter earlier, and I found that I needed to leave it empty to start working: https://community.home-assistant.io/t/knxd-add-on-covert-your-knx-usb-interface-into-an-ip-interface-that-can-be-used-by-ha/38108/35

Now I updated it as before, however it still throws errors:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: KNXD daemon
 KNXD daemon you can use to create a KNX/IP gateway via TPUART or USB bus adapters
-----------------------------------------------------------
 Add-on version: 0.3.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.11  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.2.2
 Home Assistant Supervisor: 2021.02.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 2-init-config: executing... 
[cont-init.d] 2-init-config: exited 0.
[cont-init.d] done.
[services.d] starting services
libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/003, errno=1
[services.d] done.
```

**Comment by da-anda** [comment]
is `/dev/bus/usb/001/003` actually the correct device? Please check in the supervisor hardware info which of the USB devices reported there is the correct one for you and then enter this device path in the config. It's quite likely that due to the OS and supervisor changes the devices reported to the containers changed and knxd now has difficulties to find the correct one

**Comment by lukaszolek** [comment]
Thanks for the hint - I did't know where to check it. However, it seems that the address is correct:
```
  - name: 1-1.3
    sysfs: >-
      /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3
    dev_path: /dev/bus/usb/001/003
    subsystem: usb
    by_id: null
    attributes:
      BUSNUM: '001'
      DEVNAME: /dev/bus/usb/001/003
      DEVNUM: '003'
      DEVPATH: >-
        /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3
      DEVTYPE: usb_device
      DRIVER: usb
      ID_BUS: usb
      ID_FOR_SEAT: usb-platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_3
      ID_MODEL: KNX-USB_Data_Interface
      ID_MODEL_ENC: KNX-USB\x20Data\x20Interface
      ID_MODEL_ID: '0022'
      ID_PATH: 'platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3'
      ID_PATH_TAG: platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_3
      ID_REVISION: '0102'
      ID_SERIAL: Gira_Giersiepen_GmbH___Co._KG_KNX-USB_Data_Interface
      ID_USB_INTERFACES: ':030000:'
      ID_VENDOR: Gira_Giersiepen_GmbH___Co._KG
      ID_VENDOR_ENC: Gira\x20Giersiepen\x20GmbH\x20\x26\x20Co.\x20KG
      ID_VENDOR_ID: 135e
      MAJOR: '189'
      MINOR: '2'
      PRODUCT: 135e/22/102
      SUBSYSTEM: usb
      TAGS: ':seat:'
      TYPE: 0/0/0
      USEC_INITIALIZED: '2323226'
```

**Comment by da-anda** [comment]
great, my interface now also craps out as it terminates the connection every couple seconds

**Comment by da-anda** [comment]
ok, I had accidentally selected the wrong device on my end. So it's still working fine on my end.

Sorry, but no idea what's wrong for you. It could be related to the recent supervisor changes and how they forward devices to containers/add-ons. But no idea how to test/fix this since I don't own a KNX USB-interface, only an UART one, so I can't test anything here. Debugging of the issue would have to be done by someone with such a device.

**Comment by da-anda** [comment]
since I am flying blindfolded I can only do some guesses. A dev from the HA addon_dev discord mentioned that the add-on might need udev now, which I added. If you want you can check out this branch https://github.com/da-anda/hass-io-addons/tree/test to the `/addons` share of your RPI and give it a try.

**Comment by lukaszolek** [comment]
Is it possible to add it with the Supervisor?

**Comment by da-anda** [comment]
if you do what I said, then yes, it will show up in the supervisor as local add-on

**Comment by lukaszolek** [comment]
I can see a local addon, however after clicking "Install", it starts spinning, but install does not finish.
Where can I find detailed logs of knxd addon?

**Comment by mariwing** [comment]
I have same USB error and same usb address reported by the supervisor.

```
  - name: 1-1.1
    sysfs: >-
      /sys/devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.0.auto/usb1/1-1/1-1.1
    dev_path: /dev/bus/usb/001/003
    subsystem: usb
    by_id: null
    attributes:
      BUSNUM: '001'
      DEVNAME: /dev/bus/usb/001/003
      DEVNUM: '003'
      DEVPATH: >-
        /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.0.auto/usb1/1-1/1-1.1
      DEVTYPE: usb_device
      DRIVER: usb
      ID_BUS: usb
      ID_MODEL: KNX-USB_Data_Interface
      ID_MODEL_ENC: KNX-USB\x20Data\x20Interface
      ID_MODEL_ID: '0024'
      ID_REVISION: '0101'
      ID_SERIAL: 135e_KNX-USB_Data_Interface
      ID_USB_INTERFACES: ':030000:'
      ID_VENDOR: 135e
      ID_VENDOR_ENC: 135e
      ID_VENDOR_ID: 135e
      MAJOR: '189'
      MINOR: '2'
      PRODUCT: 135e/24/101
      SUBSYSTEM: usb
      TYPE: 0/0/0
      USEC_INITIALIZED: '785999796854'
```

Running https://github.com/da-anda/hass-io-addons/tree/test as a local addon instead of the error message from https://github.com/da-anda/hass-io-addons/issues/12#issuecomment-775858883 I get this:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: KNXD daemon
 KNXD daemon you can use to create a KNX/IP gateway via TPUART or USB bus adapters
-----------------------------------------------------------
 Add-on version: 0.3.7
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.11  (aarch64 / odroid-n2)
 Home Assistant Core: 2021.2.2
 Home Assistant Supervisor: 2021.02.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 2-init-config: executing... 
exec: fatal: unable to exec bash
: No such file or directory
[cont-init.d] 2-init-config: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Thank for working on this, I really hope you can get it fixed. I can test more if you have any more ideas.
